---
development:
  SESSION_SECRET: 'fdqtGTNWU5KV/UtSOypezgncqS5pRk6xBW3DumRooL4b5F343sYGZsbfeLCiSf6cw7iJIVAKDPkyaswo7f2wew=='

test:
  SESSION_SECRET: 'fdqtGTNWU5KV/UtSOypezgncqS5pRk6xBW3DumRooL4b5F343sYGZsbfeLCiSf6cw7iJIVAKDPkyaswo7f2wew=='
